### PR TITLE
added redirects and made changes in UI

### PR DESCRIPTION
**Pull request by preethasri**
added redirects page
made some changes to make website responsive

### CODE REVIEW

**Review by MarkVed17 — APPROVED** [review]
Looks good!
You may proceed.

**Review by msdeshmukh009 — APPROVED** [review]
Regarding the responsiveness, the layout is breaking in between 900px to 640px.
Everything else is looking good.

**Comment by preethasri** [comment]
> Regarding the responsiveness, the layout is breaking in between 900px to 640px. Everything else is looking good.

**Comment by preethasri** [comment]
> Regarding the responsiveness, the layout is breaking in between 900px to 640px. Everything else is looking good.

sure will check that

**Pull request merged**
